[tool.poetry]
name = "books"
version = "0.1.0"
description = ""
authors = ["EvgVavilov <785vvv@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.7"
pillow = "^9.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
