name: Django CI
run-name: ${{ github.actor }} is testing this!

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DATABASE_URL: sqlite:///db.sqlite3
  POETRY_VERSION: 1.3.2

jobs:
  built_virtual_machine:
    name: Built_virtual_machine
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.10.8' ]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: run tester_test
        run: |
          cd ./project
          python3 tester_test.py

  run_unittests:

    name: Run_unittests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.10.8' ]
    needs: built_virtual_machine
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: 🔌 Poetry is installed.
        run: pip install poetry==${POETRY_VERSION}
      - name: 🔋 Dependencies are installed.
        run: poetry install
      - name: run test
        run: |
          cd ./project
          poetry run python3 manage.py test library
